// Generated by LiveScript 1.3.1
var fs, fns, library;
fs = require('fs');
fns = {
  add: function(x){
    return x[0] + x[1];
  },
  sub: function(x){
    return x[0] - x[1];
  },
  times: function(x){
    return x[0] * x[1];
  },
  div: function(x){
    return x[0] / x[1];
  },
  mod: function(x){
    return x[0] % x[1];
  },
  print: function(x){
    console.log(x[0]);
    return x[0];
  },
  prints: function(x){
    process.stdout.write(x[0]);
    return x[0];
  },
  at: function(x){
    return x[1][x[0]];
  },
  either: function(x){
    if (x[0]) {
      return x[0];
    } else {
      return x[1];
    }
  },
  both: function(x){
    if (x[0]) {
      return x[1];
    } else {
      return x[0];
    }
  },
  equal: function(x){
    return x[0] === x[1];
  },
  not: function(x){
    return !x[1];
  },
  append: function(x){
    return x[1].concat(x[0]);
  },
  length: function(x){
    return x[0].length;
  },
  greater: function(x){
    return x[0] > x[1];
  },
  lesser: function(x){
    return x[0] < x[1];
  },
  range: function(x){
    var i$, to$, results$ = [];
    for (i$ = x[0], to$ = x[1]; i$ <= to$; ++i$) {
      results$.push(i$);
    }
    return results$;
  }
};
library = {
  argv: process.argv,
  'true': true,
  'false': false,
  yes: true,
  no: false,
  head: function(a){
    return a[0][0];
  },
  map: function(a){
    return a[1].map(function(x){
      return a[0](x);
    });
  },
  add: fns.add,
  sub: fns.sub,
  mult: fns.mult,
  div: fns.div,
  mod: fns.mod,
  print: fns.print,
  prints: fns.prints,
  at: fns.at,
  'if': fns['if'],
  either: fns.either,
  both: fns.both,
  equal: fns.equal,
  not: fns.not,
  append: fns.append,
  length: fns.length,
  greater: fns.greater,
  lesser: fns.lesser,
  range: fns.range,
  '+': fns.add,
  '-': fns.sub,
  '*': fns.mult,
  '/': fns.div,
  '%': fns.mod,
  '.': fns.print,
  '._': fns.prints,
  '@': fns.at,
  '?': fns['if'],
  '^': fns.either,
  '&': fns.both,
  '=': fns.equal,
  '!': fns.not,
  '<<': fns.append,
  '_': fns.length,
  '>': fns.greater,
  '<': fns.lesser,
  '..': fns.range
};
module.exports = library;